#    ██████╗ ███████╗███████╗██╗   ██╗██████╗ ███████╗ ██████╗██████╗ ██╗██████╗ ███████╗
#    ██╔══██╗╚══███╔╝██╔════╝██║   ██║██╔══██╗██╔════╝██╔════╝██╔══██╗██║██╔══██╗██╔════╝
#    ██║  ██║  ███╔╝ ███████╗██║   ██║██████╔╝███████╗██║     ██████╔╝██║██████╔╝█████╗
#    ██║  ██║ ███╔╝  ╚════██║██║   ██║██╔══██╗╚════██║██║     ██╔══██╗██║██╔══██╗██╔══╝
#    ██████╔╝███████╗███████║╚██████╔╝██████╔╝███████║╚██████╗██║  ██║██║██████╔╝███████╗
#    ╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝
#
# Author:
#   TG: @YourBoredCat
#   VK: d.asspi4
#
# Permissions:
#   dzsubscribe.give - Возможность выдавать подписку
#   dzsubscribe.info - Возможность увидеть помощь по плагину
#   dzsubscribe.take - Возможность забрать подписку у игрока
#   dzsubscribe.reload - Возможность перезагружать плагин
# Placeholders:
#   %dzsubscribe_has% - Выводит префикс подписки
#   %dzsubscribe_time% - Выводит сколько осталось времени
#   %dzsubscribe_boolean% - Выводит boolean действия подписки
#     (т.е, если у игрока есть подписка то выводит true, если нет, то false,
#     это можно так же настроить ниже)
#

settings:
  placeholder: #Настройки Placeholder'ов
    has: #Настройка для %dzsubscribe_has%
      has-sub: '&#E646FF&l+' #Префикс если у игрока есть подписка
      has-not-sub: '' #Префикс если у игрока нет подписки
    time: #Настройка для %dzsubscribe_time%
      forever: '∞' #Выводит если у него бесконечная подсписка
      remainder: '%days%дн.' #Выводит кол-во дней до окончания подписки
      no-sub: 'Нету' #Выводит если нету подписки
    boolean: #Настройка для %dzsubscribe_boolean%
      yes-sub: 'true' #Выводит если у игрока есть подсписка
      no-sub: 'false' #Выводит если у игрока нет подписки

subscribe:
  commands-on-give: # Команды при выдаче подписки
    - "lp user %player% permission set open_unik_shop"
    - 'p give %player% 500'
  commands-on-take: # Команды при снятии подписки
    - "lp user %player% permission unset open_unik_shop"

messages:
  no-permission: "&7У Вас &#E646FF&nнедостаточно&f &7прав!" # Выводит Сообщение когда у игрока нет прав
  reload: "&7Вы &#E646FFуспешно перезагрузили &7конфигурацию!" # Выводит Сообщение когда плагин перезагружен
  no-args: # Выводит сообщение если недостаточно аргументов
    - "&#E646FFDZSubscribe &8| &7Помощь:"
    - ""
    - "&#E646FF/dzsubscribe give &8(&#E646FFигрок&8) &8(&#E646FFсрок&8) - &7выдать игроку подписку"
    - "&#E646FF/dzsubscribe take &8(&#E646FFигрок&8) - &7снять игроку подписку"
    - "&#E646FF/dzsubscribe info &8(&#E646FFигрок&8) - &7узнать, есть ли у игрока подписка, или нет"
    - "&#E646FF/dzsubscribe reload &8- &7перезагрузить плагин"
  null-player: "&7Игрок не найден." # Выводит Сообщение когда игрок не найден
  no-exists: "&7У игрока нет подписки!" # Выводит Сообщение когда у игрока нет подписки
  give-duration: "&7Вы выдали подписку игроку &#E646FF%player% &7на &#E646FF%duration%дн&7!" # Выводит Сообщение когда вы выдали игроку подписку на время
  give-forever: "&7Вы выдали подписку игроку &#E646FF%player% &#E646FF&nнавсегда&7!" # Выводит Сообщение когда вы выдали игроку подписку навсегда
  take: "&7Вы забрали подписку у игрока &#E646FF%player%&f!" # Выводит Сообщение когда вы сняли у игрока подписку
  incorrect-date: "&7Вы ввели &#E646FF&nнекорректную&7 дату!" # Выводит Сообщение когда вы ввели некорректную дату
  no-sub: "&7У игрока нет подписки!" # Выводит Сообщение когда у игрока нет подписки
  yes-sub: "&7У игрока есть подписка!" # Выводит Сообщение когда у игрока есть подписка
